# Generated by Django 3.2.4 on 2021-06-21 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0014_add_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='feature_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
