# Generated by Django 3.2.4 on 2021-06-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0015_alter_destination_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='feature_image',
            field=models.ImageField(default='default.jpg', upload_to='product_image'),
        ),
    ]
