# Generated by Django 3.2.4 on 2021-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrative_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('logo', models.ImageField(upload_to='')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='office_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('logo', models.ImageField(upload_to='')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact1',
        ),
    ]
