# Generated by Django 3.2.4 on 2021-06-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210624_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrative_contact',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='administrative_contact',
            name='website',
        ),
        migrations.AddField(
            model_name='administrative_contact',
            name='naam',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='administrative_contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
