# Generated by Django 3.2.4 on 2021-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210624_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrative_contact',
            name='naam',
        ),
        migrations.AddField(
            model_name='administrative_contact',
            name='name',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
